### ISSUE TITLE
I convert it to Swift 4 version.

### ISSUE THREAD

**Issue by eyupcimen** [jairobjunior/labs.jairobjunior.com.DeviceRotationOnlyOneViewController#4]
I convert it to Swift 4 version. However, I could not create a "pull request".

**Comment by furiosFast** [comment]
please, can you post the code?

**Comment by furiosFast** [comment]
thank you

**Comment by MohsenMoghimi** [comment]
@nefy55 you done greate job my friend but it didnt work for me . my view controller still apears in portrate mode . what shoul i do?

**Comment by eyupcimen** [comment]
@MohsenMoghimi I don't know. I worked for me
